# Generated by Django 3.0.5 on 2023-01-26 20:58

import BitEx.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=10)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('filled', models.BooleanField(default=False)),
                ('quote_filled', models.FloatField(default=0)),
                ('date_filled', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('wallet', djongo.models.fields.EmbeddedField(model_container=BitEx.models.Wallet)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
